# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://LinZhengLearn.github.io
date_format: "ordinal"
title: Marvin's Blog
subtitle: "Learning to Think, Thinking to Learn"
description: "林政的个人博客"
keywords: 
favicon: /favicon.ico
timezone: Asia/ShangHai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Zheng Lin
github_username: LinZhengLearn
location: BeiJing, China
email:  linzhengbupt@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Home

  -
    href: /categories/
    label: Category

  -
    href: /wiki/
    label: Wiki

  -
    href: /links/
    label: Link

  -
    href: /about/
    label: About

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: LinZhengLearn/LinZhengLearn.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, netease_gentie
comments_provider: netease_gentie
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
disqus_username: disqus_ozGkzSQwhQ
netease_gentie_key: 560ed243b708465d82d5a0a5f3b83da1
# 在使用网易云跟帖时可点击显示 LinZhengLearn
lazy_load_disqus : true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
